prooph_service_bus:
    command_buses:
        default_command_bus: ~
    event_buses:
        default_event_bus: ~

services:
    _defaults:
        public: false
        autowire: true

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.default_command_bus'
    Prooph\ServiceBus\EventBus: '@prooph_service_bus.default_event_bus'

    acme_command_handlers:
        resource: '../../src/Acme/Application/CommandHandler/'
        namespace: App\Acme\Application\CommandHandler\
        tags:
            - { name: 'prooph_service_bus.default_command_bus.route_target', message_detection: true }

    authentication_command_handlers:
        resource: '../../src/Authentication/Application/CommandHandler/'
        namespace: App\Authentication\Application\CommandHandler\
        tags:
            - { name: 'prooph_service_bus.default_command_bus.route_target', message_detection: true }

    acme_process_managers:
        resource: '../../src/Acme/Application/ProcessManager/'
        namespace: App\Acme\Application\ProcessManager\
        tags:
            - { name: 'prooph_service_bus.default_event_bus.route_target', message_detection: true }

    authentication_process_managers:
        resource: '../../src/Authentication/Application/ProcessManager/'
        namespace: App\Authentication\Application\ProcessManager\
        tags:
            - { name: 'prooph_service_bus.default_event_bus.route_target', message_detection: true }
