prooph_service_bus:
    command_buses:
        default_command_bus: ~

services:
    _defaults:
        public: false

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.default_command_bus'

    acme_command_handlers:
        resource: '../../src/Acme/Application/CommandHandler/'
        namespace: App\Acme\Application\CommandHandler\
        autowire: true
        tags:
            - { name: 'prooph_service_bus.default_command_bus.route_target', message_detection: true }

    authentication_command_handlers:
        resource: '../../src/Authentication/Application/CommandHandler/'
        namespace: App\Authentication\Application\CommandHandler\
        autowire: true
        tags:
            - { name: 'prooph_service_bus.default_command_bus.route_target', message_detection: true }
