App\Acme\Domain\Client\Client:
    type: entity

    id:
        id:
            type: string
            length: 36
            generator:
                strategy: NONE

    fields:
        name:
            type: string
