App\Authentication\Domain\Credentials:
    type: entity

    id:
        ownerId:
            type: string
            length: 36
            generator:
                strategy: NONE

    fields:
        login:
            type: string
        password:
            type: string
