App\Acme\Domain\Program\Participant:
    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        userId:
            type: string
            length: 36

    manyToOne:
        program:
            targetEntity: App\Acme\Domain\Program\Program
            inversedBy: participants
